window.addEventListener('layout:ready',()=>{
  const rows=document.getElementById('chitRows');
  const render=()=>{
    const status=document.getElementById('statusFilter')?.value||'All statuses';
    const q=(document.getElementById('chitSearch')?.value||'').toLowerCase();
    const list=ChitData.chits.filter(c=>(status==='All statuses'||c.status===status)&&(`${c.name} ${c.id}`.toLowerCase().includes(q)));
    if(rows) rows.innerHTML=list.map(c=>`<tr><td><div class="chit-name"><strong>${c.name}</strong><span>${c.id}</span></div></td><td><span class="badge ${c.status==='Active'?'badge-success':'badge-warning'}"><span class="dot"></span>${c.status}</span></td><td class="amount">${UI.money(c.value)}</td><td>${c.filled}/${c.members}<div class="progress" style="width:80px;margin-top:5px"><span style="width:${c.filled/c.members*100}%"></span></div></td><td>${c.status==='Active'?`${c.cycle}/${c.duration}`:'—'}</td><td>${c.nextAuction}</td><td><span class="badge badge-info">${c.strategy}</span></td><td><a class="action-link" data-open-overview>View →</a></td></tr>`).join('');
    document.getElementById('chitCount').textContent=`${list.length} chits`;
    rows?.querySelectorAll('[data-open-overview]').forEach(a=>a.onclick=()=>document.querySelector('[data-target="chit-overview"]').click());
  };
  render(); document.getElementById('statusFilter')?.addEventListener('change',render);document.getElementById('chitSearch')?.addEventListener('input',render);
  const mrows=document.getElementById('chitMemberRows'); if(mrows)mrows.innerHTML=ChitData.members.map((m,i)=>`<tr><td><div class="member-cell"><div class="avatar">${UI.initials(m.name)}</div><div><strong>${m.name}</strong><span>${m.id}</span></div></div></td><td>#${String(i+1).padStart(2,'0')}</td><td>${i<3?'<span class="badge badge-info">Won</span>':'No'}</td><td class="amount">${m.pending?UI.money(m.pending):'₹0'}</td><td><span class="badge ${m.regularity==='Regular'?'badge-success':m.regularity==='Delinquent'?'badge-danger':'badge-warning'}">${m.regularity}</span></td><td><a href="members.html" class="action-link">Member 360</a></td></tr>`).join('');
  const openCreate=()=>document.querySelector('[data-target="create-chit"]')?.click(); document.getElementById('newChit')?.addEventListener('click',openCreate); if(location.hash==='#create')openCreate();
  document.getElementById('cloneChit')?.addEventListener('click',()=>UI.modal('Clone existing chit',`<div class="form-grid"><div class="field"><label>Source Chit</label><select class="select"><option>Akshaya 10L / 20</option><option>Sree 12L / 24</option></select></div><div class="field"><label>New Start Month</label><input class="input" type="month" value="2026-10"></div></div><div class="callout" style="margin-top:14px">Structure and strategy are copied; editable dates and allowed attributes can be reviewed before save.</div>`,()=>openCreate()));
  document.getElementById('addMemberToChit')?.addEventListener('click',()=>UI.modal('Add member to chit',`<div class="field"><label>Search member</label><input class="input search" placeholder="Name, phone or member ID"></div><div class="card" style="margin-top:12px;padding:10px"><div class="member-cell"><div class="avatar">DM</div><div><strong>Divya M</strong><span>MB-10123 · Salem</span></div></div></div>`,()=>{}));
  document.getElementById('reviewChit')?.addEventListener('click',()=>UI.modal('Review before activation',`<div class="kv"><div class="kv-row"><span>Chit</span><strong>Mangalam 5L / 20</strong></div><div class="kv-row"><span>Value</span><strong>₹5,00,000</strong></div><div class="kv-row"><span>Strategy</span><strong>CALC-S3 v1.0</strong></div><div class="kv-row"><span>Members</span><strong>17 / 20</strong></div></div><div class="callout callout-warning" style="margin-top:14px">Activation is blocked until required member slots are filled.</div>`));
});
